### ISSUE TITLE
tvm_constructFirModel is missing

### ISSUE THREAD

**Issue by behinger** [TimVanMourik/OpenFmriAnalysis#9]
Hi!
I just noticed that file (tvm_constructFirModel) is not included in the repo. I don't need it at the moment, but was interested how you chose to implement it :-)
Best, Bene

**Comment by TimVanMourik** [comment]
Hi @behinger!
Ah, that's surprising, thanks for spotting! It's implemented as simple triangular basis functions. Nothing cool yet with sines and cosines. That is... if it actually appears in the repo. I'll check it out and get back to you.

**Comment by TimVanMourik** [comment]
Indeed I found the file in a different directory. I added it to the toolbox. Thanks again for pointing it out!
